spring:
  application:
    name: "Elo Tracker"
  datasource:
    url: jdbc:mysql://localhost:3306/elotracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${ELO_TRACKER_DB_USERNAME}
    password: ${ELO_TRACKER_DB_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    session:
      cookie:
        secure: false
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/elotracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    initialization-mode: always
