version: '3'
services:
  elo-tracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ELO_TRACKER_DB_USERNAME=${ELO_TRACKER_DB_USERNAME}
      - ELO_TRACKER_DB_PASSWORD=${ELO_TRACKER_DB_PASSWORD}
      - "SPRING_PROFILES_ACTIVE=docker"