apiVersion: v1
kind: Service
metadata:
  name: elo-tracker-service
spec:
  selector:
    app: elo-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elo-tracker-deployment
  labels:
    app: elo-tracker
    app.kubernetes.io/name: elo-tracker-api
    app.kubernetes.io/instance: elo-tracker-instance
    app.kubernetes.io/version: "0.9"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: elo-tracker-api
    app.kubernetes.io/managed-by: elo-tracker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elo-tracker
  template:
    metadata:
      labels:
        app: elo-tracker
    spec:
      containers:
        - name: elo-tracker-container
          image: "gcr.io/$(ELO_TRACKER_GCP_PROJECT_ID)/elo-tracker:v9"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ELO_TRACKER_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: ELO_TRACKER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: ELO_TRACKER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cloudsql-config
                  key: elo.database.name
            - name: ELO_TRACKER_INSTANCE_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: cloudsql-config
                  key: elo.instance.connection.name
            - name: ELO_TRACKER_GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: cloudsql-config
                  key: elo.gcp.project.id
            - name: ELO_TRACKER_CREDENTIALS_LOCATION
              value: file:/secrets/elotracker/credentials.json
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/elotracker
              readOnly: true
        - name: cloudsql-proxy-container
          image: "gcr.io/cloudsql-docker/gce-proxy:1.14"
          env:
            - name: ELO_TRACKER_INSTANCE_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: cloudsql-config
                  key: elo.instance.connection.name
          command:
            ["/cloud_sql_proxy",
             "-instances=$(ELO_TRACKER_INSTANCE_CONNECTION_NAME)=tcp:3306",
             "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-oauth-credentials
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: cloudsql-config
#  namespace: default
#data:
#  elo.database.name: {{database name}}
#  elo.gcp.project.id: {{ project id }}
#  elo.instance.connection.name: {{ instance connection name }}
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: mysql-credentials
#type: Opaque
#data:
#  password: {{ password }}
#  username: {{ username }}
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: cloudsql-oauth-credentials
#type: Opaque
#data:
#  credentials.json: {{ credentials }}